version: '3.4'

services:
  envolti.jurosapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000"

  envolti.calculajurosapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001"

networks:
  default:
    external:
      name: nat